spring.application.name=SampleJobApp

#H2 Database
#spring.h2.console.enabled=true
#spring.datasource.url=jdbc:h2:mem:test
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true
#spring.jpa.hibernate.ddl-auto=update

#Logging
#logging.level.org.hibernate.SQL=DEBUG
#logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

#Actuator
management.endpoints.web.exposure.include=*

#PostgreSQL (requires Docker  ? uncomment below & comment H2 above to use)
spring.datasource.url=jdbc:postgresql://localhost:5432/jobApp?options=-c%20timezone%3DAsia/Kolkata
spring.datasource.username=amit
spring.datasource.password=dbpassword
spring.datasource.hikari.connection-init-sql=SET timezone = 'Asia/Kolkata'
spring.jpa.database=POSTGRESQL
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=create-drop
#spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.jdbc.time_zone=Asia/Kolkata